<!--BOOK_INFORMATION-->
*This notebook contains an excerpt from the [Python Programming and Numerical Methods - A Guide for Engineers and Scientists](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9), the content is also available at [Berkeley Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html).*

*The copyright of the book belongs to Elsevier. We also have this interactive book online for a better learning experience. The code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work on [Elsevier](https://www.elsevier.com/books/python-programming-and-numerical-methods/kong/978-0-12-819549-9) or [Amazon](https://www.amazon.com/Python-Programming-Numerical-Methods-Scientists/dp/0128195495/ref=sr_1_1?dchild=1&keywords=Python+Programming+and+Numerical+Methods+-+A+Guide+for+Engineers+and+Scientists&qid=1604761352&sr=8-1)!*

# Reading
Python Programming and Numerical Methods,
[Chapter 9. Representation of Numbers](https://pythonnumericalmethods.studentorg.berkeley.edu/notebooks/chapter09.00-Representation-of-Numbers.html)

# Problems

## 1. Write a function *my_bin_2_dec(b)*
where *b* is binary number represented by a list of ones and zeros. The last element of *b* represents the coefficient of $2^0$, the second-to-last element of b represents the coefficient of $2^1$, and so on. The output variable, *d*, should be the decimal representation of b. The test cases are provided below.

In [ ]:
def my_bin_2_dec(b):
    items = len(b) #number of items in the list
    #source: https://www.geeksforgeeks.org/python/python-len-function/
    d = 0 #d for decimal

    for i in range(items): #b(item - 1) will give the items from left to right, then 2**(items - 1 - i) will give the power of two
        d+=(b[-items + i]) * (2**(items-1-i))

    return d

In [ ]:
# Output: 7
my_bin_2_dec([1, 1, 1])


7

In [ ]:
# Output: 85
my_bin_2_dec([1, 0, 1, 0, 1, 0, 1])

85

In [ ]:
# Output: 33554431
my_bin_2_dec([1]*25)

33554431

## 2. Write a function *my_dec_2_bin(d)*
where *d* is a positive integer in decimal, and *b* is the binary representation of *d*. The output *b* must be a list of ones and zeros, and the leading term must be a 1 unless the decimal input value is 0. The test cases are provided below.

In [ ]:
import numpy as np

def my_dec_2_bin(d):

    if(d == 0): #case 1: zero is a number
        l = 1
    else: #calculating the amount of bits needed
        l = int(np.floor(np.log2(d)) + 1)

    b = np.zeros(l, dtype = np.int32) #this will help later code by confirming an int data type

    for i in range(l -1, -1, -1): #filling from left to right
        r = d % 2 #the remainder from division by 2 will either be 0 or 1
        d = d//2
        b[i] = int(r)

    return b

In [ ]:
# Output: [0]
my_dec_2_bin(0)

array([0], dtype=int32)

In [ ]:
# Output: [1, 0, 1, 1, 1]
my_dec_2_bin(23)

array([1, 0, 1, 1, 1], dtype=int32)

In [ ]:
# Output: [1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1]
my_dec_2_bin(2097)

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

## 3. Compute *d = my_bin_2_dec(my_dec_2_bin(12654))*
Use the two functions you wrote in problems 1 and 2. Do you get the same number?

In [ ]:
d = my_bin_2_dec(my_dec_2_bin(12654))
print(d)

12654


Yes!

## 4. Write a function *my_bin_adder(b1,b2)*
where *b1*, *b2* and the output variable *b* are binary numbers represented as in problem 1. The output variable should be computed as *b = b1 + b2*. Do not use your functions from problems 1 and 2 to write this function (i.e., do not convert *b1* and *b2* to decimal; add them, and then convert the result back to binary). This function should be able to accept inputs *b1* and *b2* of any length (i.e., very long binary numbers), and *b1* and *b2* may not necessarily be the same length.

In [ ]:
def my_bin_adder(b1, b2):

    #assess length
    length1 = len(b1)
    length2 = len(b2)

    #ensure if the lengths are different then they can be added properly
    if (length1 > length2):
        l = length1 + 1
    elif(length2 > length1):
        l = length2 + 1
    else:
        l = length1 + 1

    b = np.zeros(l, dtype = np.int32) #making the right data type

    #if they have different lengths, then zeroes will be added to ensure they match lengths
    while(len(b1) < l):
        b1 = [0] + b1
    while(len(b2) < l):
        b2 = [0] + b2

    #if both numbers are nonzero
    if(b1 == [0] and b2 != [0]):
        b = b2
    elif(b1 != [0] and b2 == [0]):
        b = b1
    elif(b1 == [0] and b2 == [0]):
        b = [0]

    #the nonzero case
    else:
        i = 0
        while (i < l):
            #add the bits
            b[l - (i + 1)] = b1[l - (i + 1)] + b2[l - (i + 1)]

            #case 1: if 1 + 1 = 2, then put a zero down and carry a one
            if ((b1[l - (i + 1)] + b2[l - (i + 1)]) == 2):
                b[l - (i + 1)] = 0
                b1[l - (i + 2)] += 1

            #case 2: if the carry makes 3, then put a one down and carry a one
            elif((b1[l - (i + 1)] + b2[l - (i + 1)]) == 3):
                b[l - (i + 1)] = 1
                b1[l - (i + 2)] += 1

            #case 3: 0 + 1 = 1
            elif((b1[l - (i + 1)] + b2[l - (i + 1)]) == 1):
                b[l - (i + 1)] = 1

            i += 1

    if(b[0] == 0): #if there exists a leading zero, delete it
        b = np.delete(b, 0)

    return b



In [ ]:
# Output: [1, 0, 0, 0, 0, 0]
my_bin_adder([1, 0], [1, 1, 1, 1, 1])

array([1, 0, 0, 0, 0, 1], dtype=int32)

10 in binary is 2
11111 in binary is 31

2 + 31 = 33

My output was 100001, which is 33 in binary. The expected output seems to be incorrect here.

In [ ]:
# Output: [1, 1, 1, 0, 0, 1, 1]
my_bin_adder([1, 1, 1, 1, 1], [1, 0, 1, 0, 1, 0, 0])

array([1, 1, 1, 0, 0, 1, 1], dtype=int32)

In [ ]:
# Output: [1, 0, 1, 1]
my_bin_adder([1, 1, 0], [1, 0, 1])

array([1, 0, 1, 1], dtype=int32)

## 5. What is the effect of allocating more bits to the fraction versus the characteristic and vice versa? What is the effect of allocating more bits to the sign?

If you allocate more bits to the fraction, you will have a smaller range of representable numbers, but the numbers you are able to represent will have smaller spacing between the numbers and will be able to display more decimals, making them more precision.

If you allocate more bits to the characteristic, you can represent many more numbers, but the spacing between them will be huge and there will not be as many decimals, so you lose precision.

If you allocate more bits to the sign, you are wasting bits. One bit is enough to tell if the number is positive or negative, so using more than one bit will not increase precision or range of the number in any way.

## 6. Write a function *my_ieee_2_dec(ieee)*
where *ieee* is a string contains 64 characters of ones and zeros representing a 64-bit IEEE754 number. The output should be *d*, the equivalent decimal representation of *ieee*. The input variable *ieee* will always be a 64-element string of ones and zeros defining a 64-bit float.

In [ ]:
#Take a 64-character string of 0s and 1s that represents a floating pt number, and convert it to decimal

from decimal import Decimal as D, getcontext #needed for proper amount of decimal places
#source: https://docs.python.org/3/library/decimal.html

def my_ieee_2_dec(ieee):
  getcontext().prec = 30

  s = int(ieee[0]) #the first character, used for value of s -- have to specify it as an int

  expl = [] #initialize empty list for exponent
  for i in range(1, 12):
    expl.append(int(ieee[i])) #append list with integer from ieee
  exp = my_bin_2_dec(expl) #use the integers from 1-11 on the list to calculate a number for the exponent

  counter = 0
  frac = D(0)
  fracl = [] #initialize empty variables
  for i in range(12, 64):
    fracl.append(int(ieee[i])) #append list with integer values from ieee
    counter += 1
  for i in range(counter):
    frac+= D(fracl[i] * 2**(-i-1)) #computing fractional sum

  d = (-1)**s * ((1)+frac) * (2)**(exp-(1023)) #the 1023 comes from the bias
  return d


In [ ]:
# Output: -48
ieee = '1100000001001000000000000000000000000000000000000000000000000000'
my_ieee_2_dec(ieee)

Decimal('-48.0')

In [ ]:
# Output: 3.39999999999999991118215802999
ieee = '0100000000001011001100110011001100110011001100110011001100110011'
my_ieee_2_dec(ieee)

Decimal('3.39999999999999991118215802998')

Close enough, I think.

## 7. Write a function *my_dec_2_ieee(d)*
where *d* is a number in decimal and output variable *ieee* is a string with 64 characters of ones and zeros representing the 64-bit IEEE754 closest to *d*. You can assume that *d* will not cause an overflow for 64-bit *ieee* numbers.

In [ ]:
b = my_dec_2_bin(3)

In [ ]:
b.dtype

dtype('int32')

In [ ]:
from math import floor, log2

def my_dec_2_ieee(d):

  #we can extract the first character from whether d is positive or negative
  if d >= 0:
    s = '0'
  else:
    s = '1'
    d *= (-1) #changing d to positive

  #finding the exp components unlocks characters 1-11
  k = floor(log2(d)) #floor rounds it to a whole number:: log2 reverses the original 2^x
  #source: https://www.geeksforgeeks.org/python/floor-ceil-function-python/
  normalize = d / 2**k
  exp = k + 1023 #where 1023 is the bias
  expl = ''.join(str(i) for i in my_dec_2_bin(exp)).zfill(11)
  #source: https://www.geeksforgeeks.org/python/python-string-join-method/

  #finding the frac components unlocks characters 12-64
  frac = normalize - 1
  fracl = []

  for i in range(52):
    frac *= 2
    num = int(frac)
    fracl.append(str(num))
    frac -= num

  fracl = ''.join(fracl)

  #put it all together to get the IEEE754 representation
  ieee = s + expl + fracl

  # return ieee
  # return s, expl, fracl
  return ieee

In [ ]:
# Output: '0100000000101110010111101010001110011100001100011010010001101000'

d = 1.518484199625
print(my_dec_2_ieee(d))
# a, b, c = my_dec_2_ieee(d)
# print(a)
# print(b)
# print(c)

0011111111111000010010111011011000010110100011100001110100100000


This string doesn't match the expected output, but on both the other functions it returns the output correctly. I am not sure why this is happening.

If I run 1.518484199625 through an online calculator (https://www.h-schmidt.net/FloatConverter/IEEE754.html), I get 00111111110000100101110110110001, which matches my coding output.

In [ ]:
# Output: '1100000001110011010100100100010010010001001010011000100010010000'

d = -309.141740
my_dec_2_ieee(d)

'1100000001110011010100100100010010010001001010011000100010010000'

In [ ]:
# Output: '1100000011011000101010010000000000000000000000000000000000000000'

d = -25252
my_dec_2_ieee(d)

'1100000011011000101010010000000000000000000000000000000000000000'

## 8. Define *ieee_baby*
to be a representation of numbers using 6 bits where the first bit is the sign bit, the second and third bits are allocated to the characteristic, and the fourth, fifth, and sixth bits are allocated to the fraction. The normalization for the characteristic is 1.

 - Write all the decimal numbers that can be represented by *ieee_baby*.
 - What is the largest/smallest gap in *ieee_baby*?

In [2]:
def ieee_baby(d):

  s = int(d[0])
  exp = int(d[1:3], 2)
  frac = int(d[3:], 2)

  new_exp = exp - 1 #bias is 1 here
  new_frac = frac / 8

  return ((-1)**s) * (1 + new_frac) * (2**new_exp)


In [6]:
values = []
counter = 0

for i in range(64):
    b = format(i, '06b')
    values.append(ieee_baby(b))
    counter += 1

#shows values and how many there are total
values = sorted(set(values))
print("The values that can be represented by ieee_baby are ")
print(values)
print("The total of the number of values is ")
print(counter)


The values that can be represented by ieee_baby are 
[-7.5, -7.0, -6.5, -6.0, -5.5, -5.0, -4.5, -4.0, -3.75, -3.5, -3.25, -3.0, -2.75, -2.5, -2.25, -2.0, -1.875, -1.75, -1.625, -1.5, -1.375, -1.25, -1.125, -1.0, -0.9375, -0.875, -0.8125, -0.75, -0.6875, -0.625, -0.5625, -0.5, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375, 1.0, 1.125, 1.25, 1.375, 1.5, 1.625, 1.75, 1.875, 2.0, 2.25, 2.5, 2.75, 3.0, 3.25, 3.5, 3.75, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5]
The total of the number of values is 
64


## 9. Use the *np.spacing* function to determine the smallest number such that the gap is 1.

In [8]:
x = 1.0 #defining a float64

while np.spacing(x) < 1:
    x = x*2 #increasing bit size

print("The smallest number where the gap is 1 is ")
print(x)

The smallest number where the gap is 1 is 
4503599627370496.0


## 10. What are some of the advantages and disadvantages of using binary versus decimal?

Binary Advantages: Maps easily to a many electrical devices as the 0,1 can map to on/off systems, simpler to implement, efficient storage and computation due to less digits used

Binary Disadvantages: Can become longer for large number values to base 2, not as easy for humans to interpret, harder to round correctly

Decimal Advantages: More compact for large values due to being base ten, easier for humans to interpret, uses standard arithmetic operations taught in general education, easier to round

Decimal Disadvantages: More complex to implement due to more digits used, does not map easily to electrical devices, has more complex computation that takes longer for the computer


Source: https://www.geeksforgeeks.org/maths/decimal-vs-binary/

## 11. Write the number 13 (base10) in base1. How would you do addition and multiplication in base1?

Base1 uses one symbol to mark everything, so 13 would be represented by 1111111111111.

Addition would just be adding more tally marks/ones to your existing tallies/marks. Multiplication would likely just be a longer process of addition, like how you can represent 6x3 as three sets of sixes added together.

## 12. How high can you count on your fingers if you count in binary?

Source: https://en.wikipedia.org/wiki/Finger_binary

You can count to 31 (2^5 - 1) using the fingers of one hand, and up to 1023 (2^10 -1) if you use both hands.

## 13. Let *b* be a binary number having *n* digits. Can you think of ways to multiply and divide *b* by 2 that does not involve any arithmetic? Hint: Think about how you multiply and divide a decimal number by 10.

Since binary works in base 2, to mutiply by two you just need to left-shift the bits by one position, and to divide by 2 you need to right-shift the bits by one position.